/*CREAR LA BASE DE DATOS*/

CREATE DATABASE Bd_Familiares;

/*LLAMAR LA BASE DE DATOS*/

USE Bd_Familiares;


/*----------------------------CREAR TABLAS---------------------------*/


	CREATE TABLE USUARIO
	
	(
	nombre_usuario VARCHAR (50),
	passwordusuario VARCHAR (50),
	PRIMER_NOMBRE VARCHAR (50),
	SEGUNDO_NOMBRE VARCHAR (50),
	PRIMER_APELLIDO VARCHAR (50),
	SEGUNDO_APELLIDO VARCHAR (50),
	TIPO_IDENTIFICACION VARCHAR (50),
	NUM_IDENTIFICACION VARCHAR (50),
	EDAD VARCHAR (50),
	estadoUS VARCHAR (45),
	
	PRIMARY KEY (NUM_IDENTIFICACION)
	);


	CREATE TABLE PERSONAS_FAMILIARES
	
	(
	PARENTESCO VARCHAR (50),
	PRIMER_NOMBRE VARCHAR (50),
	SEGUNDO_NOMBRE VARCHAR (50),
	PRIMER_APELLIDO VARCHAR (50),
	SEGUNDO_APELLIDO VARCHAR (50),
	TIPO_IDENTIFICACION VARCHAR (50),
	NUME_IDENTIFICACION VARCHAR (50),
	EDAD VARCHAR (50),
	estadoP VARCHAR (45),
	
	PRIMARY KEY (NUME_IDENTIFICACION)
	
	);
	
	



/*---------------------INSERTAR DATOS-------------------------*/
		


	/*CONTRASEÑA ENCRIPTADA CON MD5  -- passwordusuario*/
	
	INSERT INTO	USUARIO (nombre_usuario, passwordusuario, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, TIPO_IDENTIFICACION, NUM_IDENTIFICACION, EDAD, estadoUS)
		VALUES	('USUARIO1', 'nexarte', 'JUAN', 'CAMILO', 'CASTILLO', 'ORJUELA', 'CC', '100000399', '21', 'activo'),
			('USUARIO2', 'nexarte', 'CARMEN', 'JULIANA', 'HERNANDEZ', 'PEREZ', 'CC', '100000398', '20', 'activo');
		

	INSERT INTO	PERSONAS_FAMILIARES (PARENTESCO, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, TIPO_IDENTIFICACION, NUME_IDENTIFICACION, EDAD, estadoP)
		VALUES	('HERMANO', 'JUAN', 'CAMILO', 'CASTILLO', 'ORJUELA', 'CC', '100000399', '21', 'activo'),
			('PRIMA', 'CARMEN', 'JULIANA', 'HERNANDEZ', 'PEREZ', 'CC', '100000398', '20', 'activo');




SELECT * FROM USUARIO;
SELECT * FROM PERSONAS_FAMILIARES;

